### ISSUE TITLE
Hacer que posicion no viole la ley de Demeter

### ISSUE THREAD

**Issue by GelosoFederico** [GelosoFederico/Algoritmos-3-TP-2#18]
(Planning) Pasar distancia a un metodo privado en posicion y hacer en el metodo que lo calcule lo que le pasas como parametro.

El metodo privado en Posicion tendria:  y le pasaria la posicion tuya en x e y
distanciaAPuntoEnCoordenadasCartesianas(x,y){
int distancia_x = abs(this.posicionEnX()-otraPosicion.posicionEnX());
        int distancia_y = abs(this.posicionEnY()-otraPosicion.posicionEnY());

return max(distancia_x,distancia_y);
}

**Comment by tomasBustamante** [comment]
Inspiración: https://campus.fi.uba.ar/mod/forum/discuss.php?d=66715

**Comment by GelosoFederico** [comment]
Merged in #30
