### ISSUE TITLE
Hacer que Ataque se implemente con un Strategy asignada segun condiciones.

### ISSUE THREAD

**Issue by GelosoFederico** [GelosoFederico/Algoritmos-3-TP-2#23]
Antes de atacar con el jinete este debe fijar la estrategia segun la condicion.  Las demas van a tener la cosa ya definida.

**Comment by cristinakuo** [comment]
Ya esta aplicado el Strategy de ataque para cada subclase de Unidad, en particular para jinete hay 2 tipos de ataques: Espada y ArcoYFlecha.

Falta algo para poder verificar si de cerca hay algun soldado o no, o si no hay ningun enemigo cerca, esas cosas que sirven para determinar si un ataque puede ser usado.

Propongo que se le pida a Tablero que te devuelva un conjunto de Unidades cercanas. 
Y pedirle al conjunto de Unidades si hay un soldado aliado o si hay enemigos.

**Comment by GelosoFederico** [comment]
Closed in #63
