### ISSUE TITLE
Refactor-Tablero: Inicialización 

### ISSUE THREAD

**Issue by cristinakuo** [GelosoFederico/Algoritmos-3-TP-2#34]
Se inicializa con 20x20 casilleros, cada cual tiene una posición y ninguna unidad asignada.

**Comment by GelosoFederico** [comment]
Esto se va a quedar igual, la diferencia es que tiene que ser singleton

**Comment by GelosoFederico** [comment]
Y si es Singleton hay que ver como usarlo en los tests. La forma con juego fue ponerle un método de reiniciar() que cree la instancia de nuevo. Si usamos eso hay que ponerlo con @Before en los tests.
