### ISSUE TITLE
Refactor-Tablero: Unidad, movimiento

### ISSUE THREAD

**Issue by GelosoFederico** [GelosoFederico/Algoritmos-3-TP-2#35]
Las unidades deben moverse a través de Tablero pasando la dirección y a si mismas. Tablero debe buscar donde están y de ahí moverlas.
Cambiar los tests de Unidad para reflejar esto-

**Comment by cristinakuo** [comment]
Me mergee las cosas del branch Direccion-issue-#13 para aplicarlas de paso
