### ISSUE TITLE
Refactor-Tablero tests: hacer un reset para el Singleton en vez re reinicializar

### ISSUE THREAD

**Issue by cristinakuo** [GelosoFederico/Algoritmos-3-TP-2#38]
Se puede intentar implementar esto:

[http://blog.davidehringer.com/testing/test-driven-development/unit-testing-singletons/](url)

`@Before
    public void resetMySingleton() throws SecurityException,
            NoSuchFieldException, IllegalArgumentException,
            IllegalAccessException {
        Field instance = MySingleton.class.getDeclaredField("instance");
        instance.setAccessible(true);
        instance.set(null, null);
    }`

**Comment by GelosoFederico** [comment]
Closed in #74
