### ISSUE TITLE
Ahora al colocar una unidad tira NullPointerException

### ISSUE THREAD

**Issue by cristinakuo** [GelosoFederico/Algoritmos-3-TP-2#98]
Clickeando en el boton de unidad y luego en un casillero, tira el siguiente mensaje:

`Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at main.modelo.juego.EquipoBlanco.colocar(EquipoBlanco.java:13)
`

**Comment by GelosoFederico** [comment]
Tenemos que cambiar todo de cómo se ponen las unidades y dónde van los handlers. Estoy con eso ahora

**Comment by GelosoFederico** [comment]
Iría esto con #95
